# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: GoTool@0
  inputs:
    version: '1.19'
- task: CmdLine@2
  inputs:
    script: |
      git clone https://github.com/sigstore/cosign
      cd cosign
      go install ./cmd/cosign
      $(go env GOPATH)/bin/cosign

- task: CmdLine@2
  inputs:
    script: 'cosign help'
- task: Docker@2
  inputs:
    containerRegistry: 'demoappContainerRegistery'
    repository: 'hello-world'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- script: cosign generate-key-pair -kms "azurekms://cosigndemo.vault.azure.net/cosignkey"

- script: which cosign 

- script: cosign sign -key "azurekms://cosign.vault.azure.net/cosignkey" cosigndemoacr.azurecr.io/nginx:v1