# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# - task: GoTool@0
#   inputs:
#     version: '1.19'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'cosign'
    KeyVaultName: 'cosigndemo'
    SecretsFilter: '*'
    RunAsPreJob: true



- task: CmdLine@2
  inputs:
    script: |
      wget "https://github.com/sigstore/cosign/releases/download/v2.0.0/cosign-linux-amd64"
      chmod +x cosign-linux-amd64
- script: ls
- task: CmdLine@2
  inputs:
    script: ./cosign-linux-amd64 help


# - task: Docker@2
#   inputs:
#     containerRegistry: 'demoappContainerRegistery'
#     command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'cosigndemoacr'
    repository: 'hello-world'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- script: export AZURE_CLIENT_SECRET=Yqp8Q~VoHJMXmFOXjENxLFC7sHLWWugZD.WcOa-k
- script: export AZURE_CLIENT_ID=e287926e-b744-4534-8f96-ca3df4be459e

# - script: ./cosign-linux-amd64 generate-key-pair -kms "azurekms://cosigndemo.vault.azure.net/cosignkey"

# - script: which ./cosign-linux-amd64 

- script: ./cosign-linux-amd64 sign -key "azurekms://cosign.vault.azure.net/cosignkey" cosigndemoacr.azurecr.io/hello-world:latest