# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: GoTool@0
  inputs:
    version: '1.19'
- task: CmdLine@2
  inputs:
    script: |
      wget "https://github.com/sigstore/cosign/releases/download/v2.0.0/cosign-linux-amd64"
      chmod +x cosign-linux-amd64
- script: ls
- task: CmdLine@2
  inputs:
    script: ./cosign-linux-amd64 help
- task: Docker@2
  inputs:
    containerRegistry: 'demoappContainerRegistery'
    repository: 'hello-world'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- script: ./cosign-linux-amd64 generate-key-pair -kms "azurekms://cosigndemo.vault.azure.net/cosignkey"

- script: which ./cosign-linux-amd64 

- script: ./cosign-linux-amd64 sign -key "azurekms://cosign.vault.azure.net/cosignkey" cosigndemoacr.azurecr.io/nginx:v1